# config-defaults.yaml
# sample config defaults file
epochs:
  desc: Number of epochs to train over
  value: 100
batch_size:
  desc: Size of each mini-batch
  value: 32
squad_version:
  desc: squad dataset version (1 or 2)
  value: 1
html_template:
  desc: template for generating an HTML file from a piece of text
  value: "pixel_block.html.jinja"
