# config-defaults.yaml
# sample config defaults file
epochs:
  desc: Number of epochs to train over
  value: 100
batch_size:
  desc: Size of each mini-batch
  value: 32
squad_version:
  desc: squad dataset version (1 or 2)
  value: 1


# image generation settings
html_question_template:
  desc: template for generating an HTML file from a piece of text for the question part of squad
  value: "question_block.html.jinja"
html_context_template:
  desc: template for generating an HTML file from a piece of text for the context part of squad
  value: "context_block.html.jinja"
long_context_generation_method:
  desc: method used by the generation function to handle long context
  value: "first_crop"  
max_margins:
  desc: maximum size of margin at the edges of the scan = [left, right, top, bottom]
  value: [15, 15, 3, 0]
margins_probability:
  desc: probabity of adding white margins to the scan
  value: 0.4
image_resolution:
  desc: DPI of the generated image
  value: 96
channel:
  desc: format of the generated image
  value: "GRAYSCALE"
image_height:
  desc: height of the image
  value: 368
image_width:
  desc: width of the image
  value: 368
maximal_white_space_in_image:
  desc: maximal allowed white margin at the bottom of the image
  value: 68
max_seq_length:
  desc: maximal sequence length in tokens
  value: 529
min_paragraph_length:
  desc: minimal length of text in paragraph, in characters
  value: 200
font_list_path:
  desc: path to a csv containing a list of fonts to use
  value: fonts/antique_fonts.csv
max_snippet_length:
  desc: number of characters to take from each text sample to generate a scan from
  value: 20000
mask_block_probability:
  desc: ratio of patches to be masked
  value: 0.25
mask_block_size:
  desc: size of each masked block, each made of patches of size patch_base_size
  value: [32, 16]
mask_max_merged_blocks_size:
  desc: maximum number of masked blocks merged together on each axis
  value: [2, 6]
mask_min_merged_blocks_size:
  desc: minimum number of masked blocks merged together on each axis
  value: [1, 2]
patch_base_size:
  desc: size in pixels of each patch
  value: [16, 16]
num_patches: 
  desc: number of patches in each scan
  value: 529
random_font_probability:
  desc: probability to replace font mid scan
  value: 0.5

# augmentations config
bleed_through_probability:
  desc: probability to apply bleed-through effect
  value: 0.15
max_bleed_offset:
  desc: maximal translation offset for bleed-through effect
  value: 10
bleed_alpha_mean:
  desc: mean alpha value (transperancy) of bleed effect
  value: 0.86
bleed_alpha_std:
  desc: alpha value std (transperancy) of bleed effect
  value: 0.05
bleed_gamma:
  desc: gamma value (not sure what it does) for bleed effect
  value: 0.0
random_line_length_min:
  desc: min length of random lines
  value: 250
random_horisontal_line_length_min:
  desc: min length of random lines
  value: 50
random_line_max_width:
  desc: maximum width in pixels of random line
  value: 5
salt_and_pepper_pixel_max_probability:
  desc: intensity of salt and pepper noise
  value: 0.01
blobs_num_max:
  desc: the greater the number, the less spherical the blob is
  value: 6
blobs_mask_size_max:
  desc: max size of the water damage marks
  value: 100
channel_noise_std:
  desc: for converting b&w image to color image, determines the "colorfulness" of it
  value: 0.03
random_line_horizontal_probability:
  desc: probability of adding random horizontal line
  value: 0.2
random_line_vertical_probability:
  desc: probability of adding random vertical line
  value: 0.3
noise_probability:
  desc: probability of applying pixel level noise
  value: 0.3
cloud_probability:
  desc: probability of adding random water damage to the figure
  value: 0.3
blobs_probability:
  desc: probability of adding large black holes to the figure
  value: 0.1
pepper_spots_probability:
  desc: probability of adding small black holes to the figure
  value: 0.3
blur_max_sigma:
  desc: Maximum sigma of the gaussian blur
  value: 3
blur_probability:
  desc: probability of applying blur
  value: 0.3
rotation_max_degrees:
  desc: Maximum rotation angle in degrees
  value: 5.0
rotation_probability:
  desc: probability of applying rotation
  value: 0.2
color_jitter_probability:
  desc: color_jitter_probability
  value: 0.4